project_id = "tprmiyclgmkyujswyotr"

[functions.check-rls-policies]
verify_jwt = true

[functions.process-knowledge-file]
enabled = true
verify_jwt = false
import_map = "./functions/import_map.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-knowledge-file/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-knowledge-file/*.html" ]

[functions.process-extracted-text]
enabled = true
verify_jwt = true
import_map = "./functions/process-extracted-text/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-extracted-text/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-extracted-text/*.html" ]

[functions.hello-cli-test]
verify_jwt = false
import_map = "./functions/import_map.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hello-cli-test/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hello-cli-test/*.html" ]
