// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://tprmiyclgmkyujswyotr.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcm1peWNsZ21reXVqc3d5b3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjczODIsImV4cCI6MjA2MTY0MzM4Mn0.yjzJR2P2Ma_CQ8oqWsNSY8yqpLi6bZnNdsV78lXxL6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    detectSessionInUrl: true
  }
});

// Log supabase configuration for debugging
console.log('Supabase Client Configured:', {
  url: SUPABASE_URL,
  hasKey: !!SUPABASE_PUBLISHABLE_KEY
});

// Add TypeScript support for RPC functions
declare module '@supabase/supabase-js' {
  interface SupabaseClient {
    rpc<T = any>(
      fn: SupabaseRPC.AvailableFunctions,
      params?: object,
      options?: any
    ): any;
  }
}
