// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Database } from '@/types/supabase';

// Removido import.meta.env e adicionado hardcoding
const supabaseUrl = "https://tprmiyclgmkyujswyotr.supabase.co";
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcm1peWNsZ21reXVqc3d5b3RyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNjczODIsImV4cCI6MjA2MTY0MzM4Mn0.yjzJR2P2Ma_CQ8oqWsNSY8yqpLi6bZnNdsV78lXxL6k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Tipando o cliente com <Database>
// Usando as constantes hardcoded
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    detectSessionInUrl: true
  },
  global: {
    fetch: (url, options) => {
      // console.log('Supabase Fetch Request:', url); // Comentado log fetch para produção
      return fetch(url, options);
    }
  }
});

// Log supabase configuration for debugging
console.log('Supabase Client Configured:', {
  url: supabaseUrl,
  hasKey: !!supabaseAnonKey
});

// Add TypeScript support for RPC functions
declare module '@supabase/supabase-js' {
  interface SupabaseClient {
    rpc<T = any>(
      fn: SupabaseRPC.AvailableFunctions,
      params?: object,
      options?: any
    ): any;
  }
}

// Remover logs de import.meta.env que não são mais relevantes
// console.log("[Supabase Client] Raw import.meta.env:", import.meta.env);
// console.log("[Supabase Client] VITE_SUPABASE_URL:", import.meta.env.VITE_SUPABASE_URL);
// console.log("[Supabase Client] VITE_SUPABASE_ANON_KEY:", import.meta.env.VITE_SUPABASE_ANON_KEY);
